<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class BloodValueDefinitionsTableSeeder extends Seeder
{
    public function run(): void
    {
        // Tabelle zuerst leeren (optional)
        DB::table('blood_value_definitions')->delete();

DB::table('blood_value_definitions')->insert([
            [
                'id' => 1,
                'name' => 'Ferritin',
                'unit' => 'ng/ml',
                'reference_min' => 30,
                'reference_max' => 400,
                'info' => 'Ferritin ist ein Protein, das Eisen speichert und vor allem zur Beurteilung der Eisenspeicher im Körper verwendet wird.',
                'allowed_units' => json_encode(['ng/ml', 'µg/l']),
                'conversion_factors' => json_encode(['ng/ml' => 1, 'µg/l' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Hämoglobin',
                'unit' => 'g/dl',
                'reference_min' => 12,
                'reference_max' => 16,
                'info' => 'Hämoglobin ist ein Protein in roten Blutkörperchen, das Sauerstoff von der Lunge in den Körper transportiert.',
                'allowed_units' => json_encode(['g/dl', 'g/l', 'mmol/l']),
                'conversion_factors' => json_encode(['g/dl' => 1, 'g/l' => 10, 'mmol/l' => 0.6206]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Vitamin D',
                'unit' => 'ng/ml',
                'reference_min' => 30,
                'reference_max' => 100,
                'info' => 'Vitamin D ist wichtig für den Knochenstoffwechsel, das Immunsystem und die Muskelfunktion.',
                'allowed_units' => json_encode(['ng/ml', 'nmol/l']),
                'conversion_factors' => json_encode(['ng/ml' => 1, 'nmol/l' => 2.5]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Calcium',
                'unit' => 'mmol/l',
                'reference_min' => 2.18,
                'reference_max' => 2.6,
                'info' => 'Calcium ist wichtig für Knochen, Muskeln, Nervenleitung und Blutgerinnung.',
                'allowed_units' => json_encode(['mmol/l', 'mg/dl']),
                'conversion_factors' => json_encode(['mmol/l' => 1, 'mg/dl' => 4]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'C-reaktives Protein',
                'unit' => 'mg/l',
                'reference_min' => 0.5,
                'reference_max' => 5,
                'info' => 'CRP ist ein Entzündungsmarker im Blut und hilft bei der Diagnose von akuten und chronischen Entzündungen.',
                'allowed_units' => json_encode(['mg/l', 'mg/dl']),
                'conversion_factors' => json_encode(['mg/l' => 1, 'mg/dl' => 10]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Erythrozyten',
                'unit' => 'mrd/ml',
                'reference_min' => 4.57,
                'reference_max' => 5.98,
                'info' => 'Erythrozyten sind rote Blutkörperchen, die Sauerstoff transportieren.',
                'allowed_units' => json_encode(['mrd/ml', 't/l', 'mio./µl']),
                'conversion_factors' => json_encode(['mrd/ml' => 1, 't/l' => 1, 'mio./µl' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Hämatokrit',
                'unit' => '%',
                'reference_min' => 36,
                'reference_max' => 48,
                'info' => 'Der Hämatokrit gibt den Anteil der roten Blutkörperchen am Gesamtblutvolumen an.',
                'allowed_units' => json_encode(['%']),
                'conversion_factors' => json_encode(['%' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'MCV',
                'unit' => 'fl',
                'reference_min' => 80,
                'reference_max' => 95,
                'info' => 'MCV (Mean Corpuscular Volume) gibt das durchschnittliche Volumen der roten Blutkörperchen an.',
                'allowed_units' => json_encode(['fl']),
                'conversion_factors' => json_encode(['fl' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'MCH',
                'unit' => 'pg',
                'reference_min' => 27,
                'reference_max' => 33,
                'info' => 'MCH (Mean Corpuscular Hemoglobin) gibt die durchschnittliche Hämoglobinmenge pro rotem Blutkörperchen an.',
                'allowed_units' => json_encode(['pg']),
                'conversion_factors' => json_encode(['pg' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'MCHC',
                'unit' => 'g/dl',
                'reference_min' => 32,
                'reference_max' => 36,
                'info' => 'MCHC (Mean Corpuscular Hemoglobin Concentration) beschreibt die durchschnittliche Hämoglobinkonzentration der Erythrozyten.',
                'allowed_units' => json_encode(['g/dl', 'g/l', 'mmol/l']),
                'conversion_factors' => json_encode(['g/dl' => 1, 'g/l' => 10, 'mmol/l' => 0.6206]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Leukozyten',
                'unit' => 'mrd/l',
                'reference_min' => 4,
                'reference_max' => 10,
                'info' => 'Leukozyten (weiße Blutkörperchen) sind Teil des Immunsystems und helfen bei der Abwehr von Infektionen.',
                'allowed_units' => json_encode(['mrd/l']),
                'conversion_factors' => json_encode(['mrd/l' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Thrombozyten',
                'unit' => 'tsd/µl',
                'reference_min' => 150,
                'reference_max' => 450,
                'info' => 'Thrombozyten (Blutplättchen) sind wichtig für die Blutgerinnung.',
                'allowed_units' => json_encode(['tsd/µl', 'g/l']),
                'conversion_factors' => json_encode(['tsd/µl' => 1, 'g/l' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'GFR',
                'unit' => 'ml/min',
                'reference_min' => 90,
                'reference_max' => 120,
                'info' => 'Die glomeruläre Filtrationsrate (GFR) zeigt die Nierenfunktion an und ist ein zentraler Wert zur Einschätzung der Nierengesundheit.',
                'allowed_units' => json_encode(['ml/min']),
                'conversion_factors' => json_encode(['ml/min' => 1]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}